### ISSUE TITLE
Not all components or modules finded after run

### ISSUE THREAD

**Issue by pavlosidelov** [aloncohen1/whatsapp-analyzer#2]
When I run the app 2 issues arise:
1 - AttributeError: partially initialized module 'smart_open' has no attribute 'local_file' (most likely due to a circular import)
2 - NameError: name 'botocore' is not defined

Before running the script with
streamlit run Home.py

I have setup all from
pip3 install -r requirements.txt

Direct setup of smart-open and botocore did not help.

Please advise.

![Screenshot from 2024-02-26 09-34-06](https://github.com/aloncohen1/chat-analyzer/assets/3640173/7a69b5d6-95f7-4a60-abc5-4d37b01908e6)

**Comment by aloncohen1** [comment]
This issue related to your local environment
looks like your code fails at `import gensim`

Try to follow this StackOverflow item: https://stackoverflow.com/questions/61182206/module-smart-open-has-no-attribute-local-file
